services:
  # Base de Datos PostgreSQL
  - type: pserv
    name: bd_tienda
    env: postgres
    plan: free

  # Backend (Node.js/Express)
  - type: web
    name: backend-gestion-productos
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bd_tienda
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  # Frontend (Static Site)
  - type: static
    name: frontend-gestion-productos
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://backend-gestion-productos.onrender.com/api